baseURL = "https://bewatertheater.cn"
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]
defaultContentLanguage = "en"
theme = "hugo-scroll"
title = "Be Water Theater"

[params]
    copyright = "© BeWaterTheater"
    description = "Play Drama & Have Fun"
    favicon = "images/favicon.png"
    title = "Be Water Theater"
    # hidedesignbyline = true

    [params.meta]
        keywords = "some, keywords, for, seo, you, know, google, duckduckgo, and, such"